package com.cly.model;

public class YellowObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.program
     *
     * @mbggenerated
     */
    private String program;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.video
     *
     * @mbggenerated
     */
    private String video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.program
     *
     * @return the value of test.program
     *
     * @mbggenerated
     */
    public String getProgram() {
        return program;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.program
     *
     * @param program the value for test.program
     *
     * @mbggenerated
     */
    public void setProgram(String program) {
        this.program = program == null ? null : program.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.video
     *
     * @return the value of test.video
     *
     * @mbggenerated
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.video
     *
     * @param video the value for test.video
     *
     * @mbggenerated
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.img
     *
     * @return the value of test.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.img
     *
     * @param img the value for test.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.title
     *
     * @return the value of test.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.title
     *
     * @param title the value for test.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}